name: Cập nhật mật khẩu cấp 2

on:
  workflow_dispatch:
    inputs:
      new_password:
        description: 'Nhập mật khẩu cấp 2 mới'
        required: true
        type: string

jobs:
  update-password:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        
      - name: Update password in index.html
        run: |
          sed -i "s/if (pwd === '.*') { \/\/ SYS_PWD_L2/if (pwd === '${{ github.event.inputs.new_password }}') { \/\/ SYS_PWD_L2/" index.html

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git commit -m "Update System Password Level 2"
          git push
